### ISSUE TITLE
Simplify and Correct Adder/Subtractor Functions for Segment LSLR Search

### ISSUE THREAD

**Issue by lrennels** [raddleverse/MimiBRICK.jl#19]
As of now we use auxiliary functions to provide the nearest latitude and longitude of a given point in order to search for the nearest possible local sea level rise fingerprint:

```
lon_subtractor = subtractor(1,360)
lon_adder = adder(360)
lat_adder = adder(180)
lat_subtractor = subtractor(1,180)
```

(1) I think `lon_subtractor` should run from 0 to 360 ie. `lon_subtractor = subtractor(1,360)`
(2)  The latitude functions here are assuming latitude runs from 0 to 180, but it should run from -90 to 90, indicating we should be using `lat_subtractor = subtractor(-90, 90)` and the `lat_adder` needs to loop back to -90 instead of 0.

**Comment by lrennels** [comment]
@tonyewong I suggest we do the following replacement for these functions ...

```

# assumes latitude runs from -90 to 90
function next_lat(lat::Float64, inc::Int64, direction::Symbol)
    if lat < -90 || lat > 90 
        error("Latitude must be between -90 and 90")
    end

    if direction == :increase
        new_lat = lat + inc
        if new_lat > 90
            new_lat = new_lat - 180 #wrap around 
        end

    elseif direction == :decrease
        new_lat = lat - inc
        if new_lat < -90
            new_lat = new_lat + 180
        end
    end
    return new_lat
end

# assumes longitude runs from 0 to 360
function next_lon(lon::Float64, inc::Int64, direction::Symbol)
    if lon < 0 || lon > 360
        error("Longitude must be between 0 and 360")
    end

    if direction == :increase
        new_lon = lon + inc
        if new_lon > 360
            new_lon = new_lon - 360
        end
    elseif direction == :decrease
        new_lon = lon - inc
        if new_lon < 0
            new_lon = new_lon + 360
        end
    end
    return new_lon
end
```

**Comment by lrennels** [comment]
Note that the above mirrors the same approach as was intended by the original.  There are likely other options like just finding a least squares distance to the closest available ocean point that we could consider, for now I just stuck to the expanding box around the point approach.

**Comment by tonyewong** [comment]
Addressed in [last commit](https://github.com/raddleverse/MimiBRICK.jl/pull/21/commits/f8ad1e82eb0a07731d59826c47e774ef1fbc33a9) in `testing` before merge.

**Comment by tonyewong** [comment]
Using suggested code from above.
