### ISSUE TITLE
adjust README instructions for package loading

### ISSUE THREAD

**Issue by vsrikrish** [raddleverse/MimiBRICK.jl#49]
@tonyewong `] add MimiBRICK` doesn't work (at least not with Julia 1.7), but `activate(".")` and `instantiate()` in `examples/` does.

**Comment by tonyewong** [comment]
needed to point to the github url. fixed now:
https://github.com/raddleverse/MimiBRICK.jl/commit/41249f0c50c7f890f387cc8180cac66ae8470437
