### ISSUE TITLE
JOSS paper: State of the field 

### ISSUE THREAD

**Issue by Zitzeronion** [raddleverse/MimiBRICK.jl#52]
@tonyewong  In the checklist for the paper appears the point:

- [x] State of the field

To check this off, I would like to ask you to add a section which compares MimiBRICK.jl to other software?
I assume that there are other probabilistic climate models even in Julia, but probably as well in Python.
Is there a quasi standard package that more than 10 different academic groups use, or does every group create their own project?

**Comment by tonyewong** [comment]
Check out the PR here: https://github.com/raddleverse/MimiBRICK.jl/pull/54#issue-1309801567
and let me know if there are further edits you'd suggest. We're being a bit cautious not to add too much to the text to stay within the 250-1000 word JOSS guidelines. Thanks!
